// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qikewhfnhkedpfdhcpmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpa2V3aGZuaGtlZHBmZGhjcG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTEwMjMsImV4cCI6MjA3NDAyNzAyM30.nNkvYcnY-Q9VW-T99BLLAFutCUg7gnjmPRKDDzjm-8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});